export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const STATUS_CREATE = "STATUS_CREATE";
export const LIST_FOR_ID = "LIST_FOR_ID";

export const LIST_SHIPPING_METHOD = "LIST_SHIPPING_METHOD";
export const ORDER_LIST_PRODUCT = "ORDER_LIST_PRODUCT";
